### PR TITLE
Adding MediaElementWebAudio backend, wavesurfer version bump and memory leak fix

### PR DESCRIPTION
**Pull request by rejochandran**
There a few changes I've made here,
Related to: #43 

1. Added 'MediaElementWebAudio' to backend option PropTypes
2. Bumped wavesurfer version to 4.1.1 (some code update in TimelinePlugin class)
3. Added `delete this._wavesurfer.backend.buffer;` to componentWillUnmount as this is a workaround for the memory leak issues in wavesurfer Ref: [#1940](https://github.com/katspaugh/wavesurfer.js/issues/1940)

Sorry for the long updates in quotes and line breaks ESLint had converted them automatically 😅 
If needed, I can remove them and raise another PR

Please review and let me know if these can be implemented

### CODE REVIEW

**Review by exocode — COMMENTED** [review]
@rejochandran Very cool, I would appreciate to see that PR merged.
😎 Is it then possible to access the `AudioContext`, `AudoElement` or `Nodes` to interact? Does this verson expose that somehow? 
I am asking because I search a way to 'connect' react-waves to an AudioAnalyzer (that one: https://audiomotion.dev/). May it depend on my low knowledge on the Audio Web API but I was not able to accomplish that, till now

**Comment by rejochandran** [comment]
Hi @exocode 
Just went through the documentation of audiomotion.dev and it provides a parameter on its constructor where you can pass an HTML Audio element and it takes the AudioContext

if there is just one instance of `<ReactWaves .. />` in your page, 

```
const audioMotion = new AudioMotionAnalyzer(
    document.getElementById('container'),
    {
        source: document.getElementsByTagName('audio')
    }
);
```
[Ref here](https://audiomotion.dev/#/?id=constructor)

You can also use the `onReady` event to instantiate the AudioAnalyzer 

Not sure if this solves because it sounds like an easy move. Let me know 🙂

**Comment by exocode** [comment]
> Hi @exocode
> Just went through the documentation of audiomotion.dev and it provides a parameter on its constructor where you can pass an HTML Audio element and it takes the AudioContext
> if there is just one instance of `<ReactWaves .. />` in your page,
> 
This is my problem: I have a list of ReactWaves tracks **_(multiple instances)_** and one Analyzer which should pass through the players. And I dont get it working. 
This is the most basic CodeSandbox example: I hope you get the idea.
https://codesandbox.io/s/multiinstance-react-waves-analyzer-example-zsnts?file=/src/MusicList.jsx

The thing is, that I don't know how to access the `audioContext` from `react-waves`, it seems that the prop `audioContext` is only a placeholder for future implmentations. I hoped that your PR could solve that issue somehow: 
I also wrote already with the "Analyzer"-guy and he repsonded:

> The audioContext alone is not enough, though. You need access to an audio node, like the MediaElementAudioSourceNode or the AnalyserNode to get the actual audio data in or out.
> The AnalyserNode is an input / output node, so I thought connecting ReactWaves's analyzer output to audioMotion's analyzer input. ReactWaves should be the one directly connected to the audio element, to have control. But this would only be possible if ReactWaves exposed its analyzer.

https://github.com/hvianna/audioMotion-analyzer/issues/7#issuecomment-704350538

I also have an open issue on this repo: https://github.com/dschoon/react-waves/issues/42

 May your PR fix that and bring others the ability to use that feature (ability to route players)
(sorry for making this noise)

**Comment by rejochandran** [comment]
Hi @exocode ,
Got the problem and thanks for the detailed explanation and codesandbox.
I'll look into this and open another PR for this feature.

**Comment by exocode** [comment]
If the underlying `<audio>`-tag is addressable, maybe through a `id`-prop, it would be way more easier, because with document.getElementById("playerId") it's possible to manipulate the AudioNode.

**Comment by rejochandran** [comment]
@exocode 
in the meantime, there is a possibility to get the audio context from the backend when ReactWaves is ready using the `getAudioContext()` method

```
<ReactWaves
      ...
      onReady={e => {
        const thisAudioContext = e.wavesurfer.backend.getAudioContext();
        this.setState({audioContexts:[...this.state.audioContexts, thisAudioContext]})
      }}
     ...
/>
```
Codesandbox: [https://codesandbox.io/s/intelligent-wright-cmxlz?file=/src/MusicList.jsx](https://codesandbox.io/s/intelligent-wright-cmxlz?file=/src/MusicList.jsx)
Click on the "Console log audio contexts" button to log all the audio contexts to the console.

**Comment by exocode** [comment]
> @exocode
> in the meantime, there is a possibility to get the audio context from the backend when ReactWaves is ready using the `getAudioContext()` method
> 
> ```
> <ReactWaves
>       ...
>       onReady={e => {
>         const thisAudioContext = e.wavesurfer.backend.getAudioContext();
>         this.setState({audioContexts:[...this.state.audioContexts, thisAudioContext]})
>       }}
>      ...
> />
> ```
> 
> Codesandbox: [https://codesandbox.io/s/intelligent-wright-cmxlz?file=/src/MusicList.jsx](https://codesandbox.io/s/intelligent-wright-cmxlz?file=/src/MusicList.jsx&expanddevtools=1)
> Click on the "Console log audio contexts" button to log all the audio contexts to the console.

Quite handy.. also possible to access the audio node that way to attach an "id" like I did in the example ? Maybe within that callback "onReady" ?
>  You need access to an audio node, like the MediaElementAudioSourceNode or the AnalyserNode to get the actual audio data in or out.

**Comment by rejochandran** [comment]
> Quite handy.. also possible to access the audio node that way to attach an "id" like I did in the example ? Maybe within that callback "onReady" ?

image

Guess yes, you can take the audio node from the context and map it to a state variable and switch then programmatically

**Comment by exocode** [comment]
ok, (for me) it was hard to find out `e.wavesurfer.backend.media` is the container, where I can attach my props.

```jsx
 const [currentPlayer, setCurrentPlayer] = useState({
    player: undefined,
    attached: false, // if attached twice, app breaks
  })

  const handlePlay = () => {
    setState({ ...state, playing: !state.playing })
    if (currentPlayer.attached === false) {
      props.audioMotion.connectAudio(currentPlayer.player)
      setTimeout(() => {
        setCurrentPlayer({ player: currentPlayer.player, attached: true })
      }, 0)
    }
    props.handlePlayState(props.index)
  }

 <ReactWaves
            onReady={e => {
                const thisAudioContext = e.wavesurfer.backend // .getAudioContext();
                var player = thisAudioContext.media
                player.id = "player" + props.index
                player.controlsList = "nodownload"
                player.crossOrigin = "anonymous"
                setCurrentPlayer({ player: player, attached: false })

                setState({
                  ...state,
                  audioContexts: [
                    ...state.audioContexts,
                    thisAudioContext.getAudioContext(),
                  ],
                })
              }}
             .......
```
And in my ListComponent I have to "resume()" the audioContext... otherwise  

```
componentDidMount() {
    this.audioContext = new (window.AudioContext || window.webkitAudioContext)()

    var analyzerDiv = document.getElementById("analyzer")
    this.audioMotion = new AudioMotionAnalyzer(analyzerDiv, {
      audioCtx: this.audioContext,
    })

    var resumeAudio = function () {
      document.removeEventListener("click", resumeAudio)
    }

    document.addEventListener("click", () => {
      if (this.audioMotion.audioCtx.state === "suspended") {
        this.audioMotion.audioCtx.resume()
      }
      resumeAudio()
    })
  }
```

Maybe someone will also struggle with this...
Thank you @rejochandran for your "backend" trick..

**Comment by lillichoung** [comment]
Hey, any update on this? Would love to get the memory leak fix in, as I can repro.

**Comment by dschoon** [comment]
Hey guys, I'm really sorry... For some reason I haven't been getting any of these notifications. Just realized there were actually a bunch of `Issues` opened the last couple of months. I'll update my settings so stuff like this doesn't happen in the future.

Thanks for using the component! Any future suggestions you have, I'm all ears.

**Comment by dschoon** [comment]
This has been released in [v4.0.0](https://www.npmjs.com/package/@dschoon/react-waves/v/4.0.0)

**Comment by dschoon** [comment]
@rejochandran I've also pushed the latest code to a branch named [v4-next](https://github.com/dschoon/react-waves/tree/v4-next). How about we use that for beta code changes?

**Comment by rejochandran** [comment]
@dschoon great! will push other changes to [v4-next](https://github.com/dschoon/react-waves/tree/v4-next)
and thank you for the merge 🙂

**Pull request merged**
